name: 'Test and Build'

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - run: npm ci
    - run: npm run test:ci
    - run: npm run build

  doctoc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.event.pull_request

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      name: Use Node.js 14
      with:
        node-version: 14
        check-latest: true
    - name: Install doctoc-check
      run: |
        npm install -g doctoc
        cp README.md README.md.orig
        npm run doctoc
        diff -q README.md README.md.orig
